# Example configuration file with default values
# Empty fields are required fields

base_model: # Name of the HF base model to use
name: # Name of the resulting adaptor

finetune:
  # cf. https://docs.axolotl.ai/docs/config-reference.html

  gpu_type: NVIDIA A40 # GPU to use e.g. NVIDIA A40
  gpus: 1 # Number of GPUs to use
  volume_in_gb: 50 # Volume size in GB
  container_disk_in_gb: 50 # Container disk in GB

  seed: # Seed for reproducibility
  output_dir: # Where to save the full fine-tuned model to
  device_map: # Device map to use when loading the model

  adapter: # Which PEFT method to use (lora, qlora, or empty for FFT)
  load_in_8bit: False # Whether to load in 8bit
  load_in_4bit: False # Whether to load in 4bit
  bf16: auto # Whether ot use bf16, or 'auto' for automatic detection
  fp16: # Whether to use fp16
  optimizer: adamw_torch_fused # Optimizer to use
  num_epochs: 1 # Number of epochs
  learning_rate: # Learning rate
  micro_batch_size: 1 # Micro batch size
  sequence_len: 512 # Maximum input length to fine-tune with
  gradient_accumulation_steps: 1 # Gradient accumulation steps
  gradient_checkpointing: False # Whether to use gradient checkpointing
  flash_attention: # Whether to use flash attention

  lora_r: # LoRA rank
  lora_alpha: # LoRA alpha
  lora_dropout: # LoRA dropout rate
  lora_target_modules: # LoRA target module list (list[str])

  tokenizer_config: # Optional tokenizer config path in case using a different tokenizer than one in base model
  special_tokens: # Special token list
    pad_token: # Pad token

  save_steps: # Leave empty to save at each epoch, integer for every N steps. float for fraction of total steps. 0 to only save final model.
  save_strategy: # Set to `no` to skip checkpoint saves, `epoch` at end of each epoch, `best` when better result is achieved, leave empty to infer from `save_steps`
  save_total_limit: # Checkpoints saved at a time
  save_only_model: # Whether to save only the model weights, skipping the optimizer.

  datasets:
    - path: # HF dataset repo
      split: # Name of dataset split to load from
      type: # The type of prompt used for training
      field_messages: # Key containing the messages
      message_field_role: # Key containing the role
      message_field_content: # Key containing the content

  # Use this for validation set
  test_datasets:
    - path: # *
      split: # *
      type: # *
      field_messages: # *
      message_field_role: # *
      message_field_content: # *
  eval_steps: # Leave empty to eval at each epoch, integer for every N steps. float for fraction of total steps

  use_wandb: # Whether to use wandb
  wandb_project: # Wandb project name
  wandb_entity: # Wandb entity
  wandb_watch: # Set to 'checkpoint'
  wandb_log_model: # "checkpoint" to log model to wandb Artifacts every `save_steps` or "end" to log only at the end of training
  hub_model_id: # Push checkpoints to hub
  hub_strategy: # How to push checkpoints to hub, recommend 'every_save' if checkpointing, 'end' otherwise

inference:

  split: test # Split of the dataset to use for inference (e.g. train, validation, test)

  gpu_type: # GPU type (e.g. NVIDIA A40) to use
  gpus: 1 # Number of GPUs to use
  volume_in_gb: 50 # Volume disk size in GB for all GPUs
  container_disk_in_gb: 50 # Container disk size in GB
  max_tokens: 2048 # Maximum number of tokens for generation

  output_file: # Local json file name to save the output too (e.g. output.json)
